server:
  port: 8000
  session:
    cookie:
      name: UISESSION


security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8070/auth/oauth/token
      userAuthorizationUri: http://localhost:8070/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8070/auth/rest/hello/principal
